image: alpine/edge
packages:
  - go
  - linux-pam-dev
sources:
  - https://github.com/emersion/maddy
tasks:
  - build: |
      cd maddy
      go build -v ./...
  - test: |
      cd maddy
      go test ./...
