contact_links:
  - name: Questions 
    url: "https://github.com/foxcpp/maddy/discussions/new?category=q-a"
    about: "Use GitHub discussions for any questions"
  - name: IRC channel
    url: "https://webchat.freenode.net/#maddy"
    about: "... or there is also an IRC channel for any discussions"
